CREATE TABLE topics(
  id BIGINT NOT NULL AUTO_INCREMENT,
  tittle VARCHAR(100) NOT NULL,
  message TEXT NOT NULL,
  creation_date DATETIME NOT NULL,
  author VARCHAR(100) NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 1,
  course VARCHAR(100) NOT NULL,
  PRIMARY KEY(id)
)